apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: pubsub
spec:
  type: pubsub.azure.servicebus
  version: v1
  metadata:
    - name: connectionString # Required when not using Azure Authentication.
      value: "Endpoint=sb://pubsub.servicebus.windows.net/;SharedAccessKeyName=RootManageSharedAccessKey;SharedAccessKey=eA1c6zOcHA2UoWWD7Jb62BsTWpCRVDTD/+ASbDkaQ6Q="
scopes:
  - usermanagementservice
  # Tobbi service-eket ide tedd be