apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: pubsub
spec:
  type: pubsub.azure.servicebus
  version: v1
  metadata:
    - name: connectionString # Required when not using Azure Authentication.
      value: "<IDE TEDD BE AZ AZURE SERVICE NAMESPACE-NEK A CONNECTION STRING-JET"
scopes:
  - usermanagementservice
  # Tobbi service-eket ide tedd be