apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: default
resources:
  - finecollectionservice-deployment.yaml
  - finecollectionservice-service.yaml
  - kafka-pubsub.yaml
  - simulation-deployment.yaml
  - trafficcontrolservice-deployment.yaml
  - trafficcontrolservice-service.yaml
  - vehicleregistrationservice-deployment.yaml
  - vehicleregistrationservice.yaml