apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: vehicleregistrationservice
  name: vehicleregistrationservice
spec:
  ports:
  - name: 6002-6002
    port: 6002
    protocol: TCP
    targetPort: 6002
  selector:
    app: vehicleregistrationservice
  type: ClusterIP
status:
  loadBalancer: {}

